---
- name: Install all tools
  hosts: localhost
  tasks:
    - name: Install tools
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - tmux
        - fzf
        - go
        - k9s
        - terraform
        - packer
        - node
        - maven
        - btop
        - jq
        - btop
        - jq
        - ncurses
    - name: Remind about other tools
      debug:
        msg: "Don't forget about... {{ item }}"
      with_items:
        - "sdkman: (https://sdkman.io/install)"
        - "cheatsheet: (https://www.mediaatelier.com/CheatSheet/)"
