---
- name: Tap external Homebrew repository, state present
  community.general.homebrew_tap:
    name: "{{ item }}"
  with_items:
    - civo/tools
    - derailed/k9s
    - hashicorp/tap
    - vmware-tanzu/carvel

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items:
    - warp
    - amethyst
    - vagrant

- name: Install Homebrew tools
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - fzf
    - go
    - golangci-lint
    - k9s
    - kubebuilder
    - terraform
    - packer
    - maven
    - btop
    - jq
    - btop
    - jq
    - ncurses
    - mas
    - k6
    - civo
    - yarn
    - aquasecurity/trivy/trivy
    - cloudfoundry/tap/cf-cli@8
    - bash
    - kbld

      # - name: Install Homebrew Cask tools
      #   community.general.homebrew_cask:
      #     name: "{{ item }}"
      #     state: present
      #   with_items:
      #     - alacritty

- name: Run script-based installations
  ansible.builtin.shell: "{{ item }}"
  with_items:
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
    - "go install github.com/go-delve/delve/cmd/dlv@latest"
    - "go install sigs.k8s.io/kind@v0.17.0"

- name: Remind about extra config for script-based installation
  debug:
    msg: "{{ item }}"
  with_items:
    - "For NodeJS, run npx install <version>"

- name: Remind about App Store login
  debug:
    msg: "Now is the time to login in the App Store"

- name: Install all App Store tools
  community.general.mas:
    id: "{{ item }}"
    state: latest
  with_items:
    - 425264550 # Disk Speed Test
    - 640199958 # Developer
    - 409183694 # Keynote
    - 1035137927 # KeyKey
    - 1278508951 # Trello
    - 823766827 # OneDrive
    - 571213070 # DaVinci Resolve
    - 462058435 # Excel
    - 682658836 # GarageBand
    - 425424353 # The Unarchiver
    - 937984704 # Amphetamine
    - 409203825 # Numbers
    - 497799835 # Xcode
    - 1147396723 # WhatsApp
    - 409201541 # Pages
    - 824183456 # Affinity Photo
    - 1475387142 # Tailscale
    - 1295203466 # Microsoft Remote Desktop
    - 1176895641 # Spark
    - 462054704 # Word

- name: Remind about other tools
  debug:
    msg: "Don't forget about... {{ item }}"
  with_items:
    - "sdkman: (https://sdkman.io/install)"
    - "cheatsheet: (https://www.mediaatelier.com/CheatSheet/)"
