---
- name: Tap external Homebrew repository, state present
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop:
    - civo/tools
    - derailed/k9s
    - vmware-tanzu/carvel
    - anchore/grype
    - anchore/syft

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop:
    - chatgpt
    - anaconda
    - redisinsight
    - obsidian
    - zed
    - arc
    - linearmouse
    - raspberry-pi-imager
    - warp
    #- amethyst
    - vagrant
    - studio-3t
    - cursor

- name: Install Homebrew casks without quarentine
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
    install_options: no-quarantine
  loop:
    - chromium

- name: Install Big Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop:
    - pgadmin4
  when:
    - install_big_components == "yes"

# To know the package id of an app, run `codesign -dr - [APP]`
- name: Post Homebrew Cask install
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=dev.zed.Zed;}'"
    - "defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false"
    - "/opt/homebrew/anaconda3/bin/conda init zsh"

- name: Install Homebrew tools
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  ignore_errors: true
  loop:
    - gh
    - stats
    - ollama
    - jesseduffield/lazydocker/lazydocker
    - operator-sdk
    - jesseduffield/lazygit/lazygit
    - ripgrep
    - slides
    - gum
    - vhs
    - neovim
    - syft
    - grype
    - tmux
    - fzf
    - go
    - golangci-lint
    - k9s
    - opentofu
    - packer
    - maven
    - btop
    - jq
    - ncurses
    - mas
    - k6
    - civo
    - yarn
    - aquasecurity/trivy/trivy
    - cloudfoundry/tap/cf-cli@8
    - bash
    - kbld

- name: Run script-based installations
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
    - "go install github.com/go-delve/delve/cmd/dlv@latest"
    - "go install sigs.k8s.io/kind@v0.22.0"

- name: Remind about extra config for script-based installation
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "For NodeJS, run npx install <version>"

- name: Remind about App Store login
  ansible.builtin.debug:
    msg: "Now is the time to login in the App Store"

# Get Max App Store app identifier using `mas search <app-name>` or via web search `mac app store <app-name>`
- name: Install all App Store tools
  community.general.mas:
    id: "{{ item }}"
    state: latest
  loop:
    - 441258766 # Magnet
    - 1452453066 # Hidden Bar
    - 425264550 # Disk Speed Test
    - 640199958 # Developer
    - 409183694 # Keynote
    - 1035137927 # KeyKey
    - 1278508951 # Trello
    - 823766827 # OneDrive
    - 571213070 # DaVinci Resolve
    - 462058435 # Excel
    - 682658836 # GarageBand
    - 425424353 # The Unarchiver
    - 937984704 # Amphetamine
    - 409203825 # Numbers
    - 497799835 # Xcode
    - 1147396723 # WhatsApp
    - 409201541 # Pages
    - 824183456 # Affinity Photo
    - 1475387142 # Tailscale
    - 1295203466 # Microsoft Remote Desktop
    - 1176895641 # Spark
    - 462054704 # Word

- name: Remind about other DEVELOPMENT tools
  ansible.builtin.debug:
    msg: "Don't forget about... {{ item }}"
  loop:
    - "sdkman: (https://sdkman.io/install)"
    - "cheatsheet: (https://www.mediaatelier.com/CheatSheet/)"
    - "rust: (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)"

- name: Remind about other MUSIC tools
  ansible.builtin.debug:
    msg: "Don't forget about... {{ item }}"
  loop:
    - "(AKAI)inMusic (https://profile.inmusicbrands.com/customer/account/productregistrations/)"
    - "(Vaults)The Crow Hill Company (https://thecrowhillcompany.com)"

- name: Remind about other 3D Printing tools
  ansible.builtin.debug:
    msg: "Don't forget about... {{ item }}"
  loop:
    - "Bambu Studio (https://bambulab.com/en/download/studio)"
